"""Update WorkflowTransition

Revision ID: 28eb30d43992
Revises: 275df70c7cc9
Create Date: 2026-07-09 17:31:16.026563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28eb30d43992'
down_revision: Union[str, None] = '275df70c7cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_transitions', sa.Column('require_note', sa.Boolean(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('require_assignment', sa.Boolean(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('require_evidence', sa.Boolean(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_transitions', 'is_active')
    op.drop_column('workflow_transitions', 'require_evidence')
    op.drop_column('workflow_transitions', 'require_assignment')
    op.drop_column('workflow_transitions', 'require_note')
    # ### end Alembic commands ###
