"""Sync models

Revision ID: 3ab7434e34ac
Revises: 34f76301c4d7
Create Date: 2026-07-09 15:31:14.651748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ab7434e34ac'
down_revision: Union[str, None] = '34f76301c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_history_id'), 'contact_history', ['id'], unique=False)
    op.create_index(op.f('ix_architectures_id'), 'architectures', ['id'], unique=False)
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_business_rules_id'), 'business_rules', ['id'], unique=False)
    op.create_index(op.f('ix_case_communications_id'), 'case_communications', ['id'], unique=False)
    op.create_index(op.f('ix_case_status_history_id'), 'case_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_cause_categories_id'), 'cause_categories', ['id'], unique=False)
    op.alter_column('classification_feedback', 'ia_classification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('classification_feedback', 'final_classification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_classification_feedback_id'), 'classification_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_communication_attachments_id'), 'communication_attachments', ['id'], unique=False)
    op.drop_constraint('contacts_customer_id_email_key', 'contacts', type_='unique')
    op.drop_constraint('contacts_functional_id_key', 'contacts', type_='unique')
    op.create_index(op.f('ix_contacts_functional_id'), 'contacts', ['functional_id'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_nit'), 'customers', ['nit'], unique=False)
    op.alter_column('dashboard_configs', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_dashboard_configs_id'), 'dashboard_configs', ['id'], unique=False)
    op.create_index(op.f('ix_general_parameters_id'), 'general_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_integration_configs_id'), 'integration_configs', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_index(op.f('ix_management_systems_id'), 'management_systems', ['id'], unique=False)
    op.create_index(op.f('ix_organizational_findings_id'), 'organizational_findings', ['id'], unique=False)
    op.alter_column('pqrsf', 'clasificacion_ia',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pqrsf', 'clasificacion_final',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('pqrsf_consecutivo_key', 'pqrsf', type_='unique')
    op.create_index(op.f('ix_pqrsf_consecutivo'), 'pqrsf', ['consecutivo'], unique=True)
    op.create_index(op.f('ix_pqrsf_id'), 'pqrsf', ['id'], unique=False)
    op.create_index(op.f('ix_pqrsf_attachments_id'), 'pqrsf_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_pqrsf_comments_id'), 'pqrsf_comments', ['id'], unique=False)
    op.create_index(op.f('ix_pqrsf_history_id'), 'pqrsf_history', ['id'], unique=False)
    op.create_index(op.f('ix_pqrsf_types_id'), 'pqrsf_types', ['id'], unique=False)
    op.create_index(op.f('ix_priorities_id'), 'priorities', ['id'], unique=False)
    op.create_index(op.f('ix_probables_causes_id'), 'probables_causes', ['id'], unique=False)
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_index(op.f('ix_sentiments_id'), 'sentiments', ['id'], unique=False)
    op.drop_constraint('sla_rules_tipo_id_prioridad_id_arquitectura_id_area_id_cust_key', 'sla_rules', type_='unique')
    op.create_index(op.f('ix_sla_rules_id'), 'sla_rules', ['id'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_workflow_state_visibility_id'), 'workflow_state_visibility', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_states_id'), 'workflow_states', ['id'], unique=False)
    op.drop_constraint('workflow_transitions_from_state_id_to_state_id_key', 'workflow_transitions', type_='unique')
    op.create_index(op.f('ix_workflow_transitions_id'), 'workflow_transitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_transitions_id'), table_name='workflow_transitions')
    op.create_unique_constraint('workflow_transitions_from_state_id_to_state_id_key', 'workflow_transitions', ['from_state_id', 'to_state_id'])
    op.drop_index(op.f('ix_workflow_states_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_state_visibility_id'), table_name='workflow_state_visibility')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_sla_rules_id'), table_name='sla_rules')
    op.create_unique_constraint('sla_rules_tipo_id_prioridad_id_arquitectura_id_area_id_cust_key', 'sla_rules', ['tipo_id', 'prioridad_id', 'arquitectura_id', 'area_id', 'customer_id'])
    op.drop_index(op.f('ix_sentiments_id'), table_name='sentiments')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_index(op.f('ix_probables_causes_id'), table_name='probables_causes')
    op.drop_index(op.f('ix_priorities_id'), table_name='priorities')
    op.drop_index(op.f('ix_pqrsf_types_id'), table_name='pqrsf_types')
    op.drop_index(op.f('ix_pqrsf_history_id'), table_name='pqrsf_history')
    op.drop_index(op.f('ix_pqrsf_comments_id'), table_name='pqrsf_comments')
    op.drop_index(op.f('ix_pqrsf_attachments_id'), table_name='pqrsf_attachments')
    op.drop_index(op.f('ix_pqrsf_id'), table_name='pqrsf')
    op.drop_index(op.f('ix_pqrsf_consecutivo'), table_name='pqrsf')
    op.create_unique_constraint('pqrsf_consecutivo_key', 'pqrsf', ['consecutivo'])
    op.alter_column('pqrsf', 'clasificacion_final',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pqrsf', 'clasificacion_ia',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_organizational_findings_id'), table_name='organizational_findings')
    op.drop_index(op.f('ix_management_systems_id'), table_name='management_systems')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_integration_configs_id'), table_name='integration_configs')
    op.drop_index(op.f('ix_general_parameters_id'), table_name='general_parameters')
    op.drop_index(op.f('ix_dashboard_configs_id'), table_name='dashboard_configs')
    op.alter_column('dashboard_configs', 'value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_customers_nit'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_functional_id'), table_name='contacts')
    op.create_unique_constraint('contacts_functional_id_key', 'contacts', ['functional_id'])
    op.create_unique_constraint('contacts_customer_id_email_key', 'contacts', ['customer_id', 'email'])
    op.drop_index(op.f('ix_communication_attachments_id'), table_name='communication_attachments')
    op.drop_index(op.f('ix_classification_feedback_id'), table_name='classification_feedback')
    op.alter_column('classification_feedback', 'final_classification',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('classification_feedback', 'ia_classification',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_cause_categories_id'), table_name='cause_categories')
    op.drop_index(op.f('ix_case_status_history_id'), table_name='case_status_history')
    op.drop_index(op.f('ix_case_communications_id'), table_name='case_communications')
    op.drop_index(op.f('ix_business_rules_id'), table_name='business_rules')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_index(op.f('ix_architectures_id'), table_name='architectures')
    op.drop_index(op.f('ix_contact_history_id'), table_name='contact_history')
    op.drop_table('contact_history')
    # ### end Alembic commands ###
