"""Add Explorer Framework fields

Revision ID: 91d4495a547e
Revises: 89c746e51d66
Create Date: 2026-07-24 03:17:29.244691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d4495a547e'
down_revision: Union[str, None] = '89c746e51d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_documents', sa.Column('current_version', sa.String(length=50), nullable=True))
    op.add_column('business_documents', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('business_documents', sa.Column('parent_document_id', sa.Integer(), nullable=True))
    op.add_column('business_documents', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('business_documents', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business_documents', 'business_documents', ['parent_document_id'], ['id'])
    op.create_foreign_key(None, 'business_documents', 'users', ['owner_id'], ['id'])
    op.add_column('document_categories', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('document_categories', sa.Column('ui_metadata', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'document_categories', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_categories', type_='unique')
    op.drop_column('document_categories', 'ui_metadata')
    op.drop_column('document_categories', 'code')
    op.drop_constraint(None, 'business_documents', type_='foreignkey')
    op.drop_constraint(None, 'business_documents', type_='foreignkey')
    op.drop_column('business_documents', 'owner_id')
    op.drop_column('business_documents', 'expires_at')
    op.drop_column('business_documents', 'parent_document_id')
    op.drop_column('business_documents', 'status')
    op.drop_column('business_documents', 'current_version')
    # ### end Alembic commands ###
