"""Fase 1 Case Domain

Revision ID: b550481a832f
Revises: dece3a6baac6
Create Date: 2026-07-20 21:56:32.250130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b550481a832f'
down_revision: Union[str, None] = 'dece3a6baac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('form_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_categories_code'), 'case_categories', ['code'], unique=True)
    op.create_index(op.f('ix_case_categories_id'), 'case_categories', ['id'], unique=False)
    op.create_table('case_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_sources_code'), 'case_sources', ['code'], unique=True)
    op.create_index(op.f('ix_case_sources_id'), 'case_sources', ['id'], unique=False)
    op.add_column('pqrsf', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pqrsf', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pqrsf', 'case_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'pqrsf', 'case_sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pqrsf', type_='foreignkey')
    op.drop_constraint(None, 'pqrsf', type_='foreignkey')
    op.drop_column('pqrsf', 'source_id')
    op.drop_column('pqrsf', 'category_id')
    op.drop_index(op.f('ix_case_sources_id'), table_name='case_sources')
    op.drop_index(op.f('ix_case_sources_code'), table_name='case_sources')
    op.drop_table('case_sources')
    op.drop_index(op.f('ix_case_categories_id'), table_name='case_categories')
    op.drop_index(op.f('ix_case_categories_code'), table_name='case_categories')
    op.drop_table('case_categories')
    # ### end Alembic commands ###
