"""Add OperationalRule and RuleExecutionLog

Revision ID: e83146de7eec
Revises: 28eb30d43992
Create Date: 2026-07-09 17:47:08.316521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83146de7eec'
down_revision: Union[str, None] = '28eb30d43992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_rules_id'), 'operational_rules', ['id'], unique=False)
    op.create_table('rule_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('workflow_version', sa.String(length=50), nullable=True),
    sa.Column('execution_window', sa.String(length=50), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['operational_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_execution_logs_id'), 'rule_execution_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_execution_logs_id'), table_name='rule_execution_logs')
    op.drop_table('rule_execution_logs')
    op.drop_index(op.f('ix_operational_rules_id'), table_name='operational_rules')
    op.drop_table('operational_rules')
    # ### end Alembic commands ###
